import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';
import 'package:mesh_mapper/utils/mvt_cells.dart';

/// Fixtures generated by the SERVER's dev/mvt_encoder.php — the decoder must
/// stay in lockstep with it (see MeshMapper_Server/docs/VECTOR_TILES.md).
///
/// `_knownTile`: layer "coverage", extent 4096, two features:
///   id=42 {i:-5, j:7, st:1} and id=43 {i:3, j:7, st:6}.
/// `_realTile`: an actual rendered z12 coverage tile (29 cells).
const _knownTile =
    'GmUKCGNvdmVyYWdlEhkIKhIGAAABAQICGAMiCwkAABoUAAAUEwAPEhsIKxIGAAMBAQIEGAMiDQnIAZADGhQAABQTAA8aAWkaAWoaAnN0IgIwCSICMA4iAjACIgIwBiICMAwogCB4Ag==';
const _realTile =
    'GuoJCghjb3ZlcmFnZRIjCM2lwuWVPxIGAAABAQICGAMiEAmMPJAgGuYCAAC6AuUCAA8SIwjOpcLllT8SBgAAAQMCAhgDIhAJ8j6QIBrmAgAAugLlAgAPEiMIzKXC5JU/EgYABAEFAgIYAyIQCaY5yiIa5gIAALoC5QIADxIjCM6lwuSVPxIGAAQBAwICGAMiEAnyPsoiGuYCAAC6AuUCAA8SIwjNpcLjlT8SBgAGAQECBxgDIhAJjDyEJRrmAgAAugLlAgAPEiMIzKXC4pU/EgYACAEFAgIYAyIQCaY5vica5gIAALoC5QIADxIjCM2lwuKVPxIGAAgBAQICGAMiEAmMPL4nGuYCAAC6AuUCAA8SIwjDpcLhlT8SBgAJAQoCCxgDIhAJkCD4KRrmAgAAugLlAgAPEiMIy6XC4ZU/EgYACQEMAgsYAyIQCcA2+Cka5gIAALoC5QIADxIjCMOlwuCVPxIGAA0BCgIHGAMiEAmQILIsGuYCAAC6AuUCAA8SIwjEpcLglT8SBgANAQ4CCxgDIhAJ9iKyLBrmAgAAugLlAgAPEiMIy6XC4JU/EgYADQEMAg8YAyIQCcA2siwa5gIAALoC5QIADxIjCM2lwuCVPxIGAA0BAQILGAMiEAmMPLIsGuYCAAC6AuUCAA8SIwjNpcLflT8SBgAQAQECCxgDIhAJjDzsLhrmAgAAugLlAgAPEiMIyqXC3pU/EgYAEQESAg8YAyIQCdozpjEa5gIAALoC5QIADxIjCMylwt6VPxIGABEBBQILGAMiEAmmOaYxGuYCAAC6AuUCAA8SIwjNpcLelT8SBgARAQECBxgDIhAJjDymMRrmAgAAugLlAgAPEiMIyqXC3ZU/EgYAEwESAgIYAyIQCdoz4DMa5gIAALoC5QIADxIjCMylwt2VPxIGABMBBQILGAMiEAmmOeAzGuYCAAC6AuUCAA8SIwjJpcLclT8SBgAUARUCCxgDIhAJ9DCaNhrmAgAAugLlAgAPEiMIyqXC3JU/EgYAFAESAgsYAyIQCdozmjYa5gIAALoC5QIADxIjCMulwtyVPxIGABQBDAILGAMiEAnANpo2GuYCAAC6AuUCAA8SIwjGpcLblT8SBgAWARcCCxgDIhAJwijUOBrmAgAAugLlAgAPEiMIx6XC25U/EgYAFgEYAgcYAyIQCagr1Dga5gIAALoC5QIADxIjCMilwtuVPxIGABYBGQILGAMiEAmOLtQ4GuYCAAC6AuUCAA8SIwjKpcLblT8SBgAWARICDxgDIhAJ2jPUOBrmAgAAugLlAgAPEiMIy6XC25U/EgYAFgEMAgsYAyIQCcA21Dga5gIAALoC5QIADxIjCMqlwtmVPxIGABoBEgICGAMiEAnaM8g9GuYCAAC6AuUCAA8SIwjJpcLYlT8SBgAbARUCAhgDIhAJ9DCCQBrmAgAAugLlAgAPGgFpGgFqGgJzdCIEMLXUASIEMJrLBCICMAwiBDCcywQiBDC31AEiBDCYywQiBDC51AEiAjAIIgQwu9QBIgQwvdQBIgQwhssEIgIwBCIEMJbLBCIEML/UASIEMIjLBCICMAIiBDDB1AEiBDDD1AEiBDCUywQiBDDF1AEiBDDH1AEiBDCSywQiBDDJ1AEiBDCMywQiBDCOywQiBDCQywQiBDDN1AEiBDDP1AEogCB4Ag==';

void main() {
  test('decodes the known two-feature tile exactly', () {
    final cells = decodeCoverageCells(base64Decode(_knownTile));
    expect(cells.length, 2);
    expect(cells[0].id, 42);
    expect(cells[0].i, -5);
    expect(cells[0].j, 7);
    expect(cells[0].st, 1);
    expect(cells[1].id, 43);
    expect(cells[1].i, 3);
    expect(cells[1].j, 7);
    expect(cells[1].st, 6);
  });

  test('decodes a real rendered tile with valid ids and categories', () {
    final cells = decodeCoverageCells(base64Decode(_realTile));
    expect(cells.length, 29);
    for (final cell in cells) {
      expect(cell.st, inInclusiveRange(1, 6));
      // id = ((i + 2^20) << 21) | (j + 2^20), computed arithmetically here
      // because dart2js truncates >32-bit bitwise ops (web build).
      final expectedId = (cell.i + 1048576) * 2097152 + (cell.j + 1048576);
      expect(cell.id, expectedId);
    }
  });

  test('garbage input decodes to empty, never throws', () {
    expect(decodeCoverageCells(base64Decode('aGVsbG8gd29ybGQ=')), isEmpty);
  });
}
